//! Build script that scans source files for Cypher queries and generates
//! an encrypted query registry. The queries are stored as XOR'd byte arrays
//! so `strings` on the binary reveals nothing.

use std::env;
use std::fs;
use std::path::Path;

const KEY: &[u8] = b"s4v4nts_m3m0ry_3ng1n3_2026_x9k2";

fn encrypt(input: &str) -> Vec<u8> {
    input.as_bytes()
        .iter()
        .enumerate()
        .map(|(i, &b)| b ^ KEY[i % KEY.len()])
        .collect()
}

fn main() {
    // Generate the obfuscation module with the key embedded
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("query_key.rs");

    // Just emit the key validation — actual query obfuscation happens
    // at runtime via the obfuscate module. The build script ensures
    // the key is consistent.
    fs::write(&dest, format!(
        "// Auto-generated by build.rs — do not edit\n\
         pub const QUERY_KEY_HASH: u64 = {};\n",
        {
            let mut hash: u64 = 5381;
            for &b in KEY {
                hash = hash.wrapping_mul(33).wrapping_add(b as u64);
            }
            hash
        }
    )).unwrap();

    println!("cargo:rerun-if-changed=build.rs");
}
