[package]
name = "savants"
version = "0.1.0"
edition = "2021"
description = "Your infrastructure savant. Know what's wrong in 60 seconds."

[[bin]]
name = "savants"
path = "src/main.rs"

[dependencies]
clap = { version = "=4.5.37", features = ["derive"] }
redis = { version = "=0.25.4", features = ["tokio-comp"] }
tokio = { version = "1.38", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
colored = "2"
dirs = "5"
